### ISSUE TITLE
Lokking for `equivalence.pdf`

### ISSUE THREAD

**Issue by bikaro** [MQLib/MQLib#9]
https://github.com/MQLib/MQLib/blob/686a4fc52b9d2037b4a9ed55fbd178cc9e60ebc3/src/problem/qubo_instance.cpp#L38-L41

In the code by the transformation from MaxCut to QUBO Instance (or the other way around) it mentions a `equivalence.pdf` in the command for details. Is this PDF available somewhere? I would be interested in having a look at it.

**Comment by josilber** [comment]
Sure, please find it attached.

Best,
John

**Comment by bikaro** [comment]
Thanks for the quick response. Unfortunately the attachment seam to have not worked as I can't find the file in the issue, can you upload it again?

**Comment by josilber2** [comment]
Sorry, let's try again with the attachment.
[equivalence.pdf](https://github.com/MQLib/MQLib/files/10934880/equivalence.pdf)
